# Generated by Django 5.2.8 on 2025-11-25 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visitas', '0003_visita_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='area',
            field=models.CharField(blank=True, choices=[('MED_GENERAL', 'Medicina General'), ('PEDIATRIA', 'Pediatría'), ('CARDIOLOGIA', 'Cardiología'), ('DERMATOLOGIA', 'Dermatología'), ('GINECOLOGIA', 'Ginecología'), ('NEUROLOGIA', 'Neurología'), ('TRAUMATOLOGIA', 'Traumatología'), ('ODONTOLOGIA', 'Odontología'), ('OTORRINO', 'Otorrinolaringología'), ('OFTALMOLOGIA', 'Oftalmología'), ('PSICOLOGIA', 'Psicología'), ('NUTRICION', 'Nutrición')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='doctor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
