# Generated by Django 5.2.8 on 2025-11-25 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visitas', '0004_visita_area_visita_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='area',
            field=models.CharField(choices=[('Urgencias', 'Urgencias'), ('Pediatría', 'Pediatría'), ('Cardiología', 'Cardiología'), ('Dermatología', 'Dermatología'), ('Radiología', 'Radiología'), ('Traumatología', 'Traumatología')], default='Urgencias', max_length=50),
        ),
        migrations.AlterField(
            model_name='visita',
            name='doctor',
            field=models.CharField(default='Sin asignar', max_length=100),
        ),
    ]
