# Generated by Django 5.2.6 on 2025-09-25 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12)),
                ('motivo', models.TextField()),
                ('hora_entrada', models.TimeField(auto_now_add=True)),
                ('hora_salida', models.TimeField()),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
