# Generated by Django 5.2.6 on 2025-09-26 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visitas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visita',
            old_name='motivo',
            new_name='motivo_visita',
        ),
        migrations.RemoveField(
            model_name='visita',
            name='fecha',
        ),
        migrations.AlterField(
            model_name='visita',
            name='hora_entrada',
            field=models.TimeField(),
        ),
    ]
