# Generated by Django 5.2.6 on 2025-09-26 01:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visitas', '0002_rename_motivo_visita_motivo_visita_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
